spring:
  profiles:
    active: prod
  data:
    mongodb:
      option:
        address: [ '$mongodbAddress' ]
        database: $mongodbDatabase
        username: $mongodbUsername
        password: $mongodbPassword

system:
  properties:
    profileActive: prod
